try :
    a = 333 / 0

except Exception as e:
    print(e)
#gets executed when there is no error in try block
else:
    print ("hello abhi")    